/**
 * Builds the registry, twice over, from one source of truth.
 *
 * 1. `shadcn build` flattens registry.json into public/r/*.json — what the CLI
 *    fetches when someone runs `shadcn add @liqui/button`.
 * 2. This script then emits registry/__index__.tsx, a lazy component map the
 *    docs site uses to render <ComponentPreview name="button-demo" />.
 *
 * Both read the same registry.json, so a demo can never drift from the code
 * that actually ships. Adding a component means editing registry.json only.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

type RegistryFile = { path: string; type: string; target?: string };
type RegistryItem = {
  name: string;
  type: string;
  title?: string;
  description?: string;
  files?: RegistryFile[];
};

const registry: { items: RegistryItem[] } = JSON.parse(
  await import('node:fs/promises').then((fs) => fs.readFile(join(appRoot, 'registry.json'), 'utf8')),
);

// --- 1. CLI payload ---------------------------------------------------------

execFileSync('pnpm', ['exec', 'shadcn', 'build', '--output', 'public/r'], {
  cwd: appRoot,
  stdio: 'inherit',
});

// --- 2. Docs component map --------------------------------------------------

// Examples and blocks are the things that render standalone — each is a file
// with a default export. A `registry:ui` item exports named parts and is never
// previewed on its own (the docs preview `button-demo`, not `button`).
const PREVIEWABLE_TYPES = new Set(['registry:example', 'registry:block']);
const previewable = registry.items.filter(
  (item) => PREVIEWABLE_TYPES.has(item.type) && item.files?.some((f) => f.path.endsWith('.tsx')),
);

const entries = previewable
  .map((item) => {
    const file = item.files!.find((f) => f.path.endsWith('.tsx'))!;
    // registry.json paths are relative to the app root; the generated index sits
    // one level down in registry/, so `@/` keeps the specifier valid either way.
    const importPath = `@/${file.path.replace(/\.tsx$/, '')}`;
    return `  "${item.name}": {
    name: "${item.name}",
    title: ${JSON.stringify(item.title ?? item.name)},
    description: ${JSON.stringify(item.description ?? '')},
    type: ${JSON.stringify(item.type)},
    source: ${JSON.stringify(file.path)},
    component: React.lazy(() => import("${importPath}")),
  },`;
  })
  .join('\n');

const index = `// Generated by scripts/build-registry.mts — do not edit.
// Regenerate with \`pnpm registry:build\` (runs automatically on dev/build).
import * as React from "react";

export interface RegistryEntry {
  name: string;
  title: string;
  description: string;
  type: string;
  source: string;
  component: React.LazyExoticComponent<React.ComponentType>;
}

export const Index: Record<string, RegistryEntry> = {
${entries}
};
`;

mkdirSync(join(appRoot, 'registry'), { recursive: true });
writeFileSync(join(appRoot, 'registry', '__index__.tsx'), index);

// --- 3. Demo source, for the code tab ---------------------------------------

// Baked in at build time rather than read with fs at render time: a dynamic
// `readFile(process.cwd() + path)` makes Next trace the entire project into the
// server bundle. This module is imported only by ComponentPreview, which is a
// server component, so the strings never reach the client — keep it that way.
const sources = previewable
  .map((item) => {
    const file = item.files!.find((f) => f.path.endsWith('.tsx'))!;
    const text = readFileSync(join(appRoot, file.path), 'utf8')
      // Demos import from where the source lives in this repo; the CLI writes
      // those files elsewhere in a consumer project, so the displayed code is
      // rewritten to match. Otherwise copy-pasting a demo yields an import that
      // resolves to nothing.
      .replace(/@\/registry\/liqui\/ui\//g, '@/components/ui/')
      .replace(/@\/registry\/liqui\/lib\//g, '@/lib/')
      .trimEnd();
    return `  ${JSON.stringify(item.name)}: ${JSON.stringify(text)},`;
  })
  .join('\n');

writeFileSync(
  join(appRoot, 'registry', '__sources__.ts'),
  `// Generated by scripts/build-registry.mts — do not edit.
// Server-only: importing this from a client component would ship every demo's
// source text to the browser.
export const Sources: Record<string, string> = {
${sources}
};
`,
);

console.log(
  `registry: ${registry.items.length} items → public/r, ${previewable.length} previewable → registry/__index__.tsx + __sources__.ts`,
);
